apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: siva  # ✅ Ensure this matches the 'labels' in your Deployment spec
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # ✅ Ensure this matches the containerPort in Deployment
  type: LoadBalancer
